export const disk_read = 'http://guanwei.zgjy518.com/Disk_read/ec595eaeec302e8b'
export const news_infomation='http://guanwei.zgjy518.com/News_information/ae84df3418730470'
export const teacher_report ='http://guanwei.zgjy518.com/Teacher_report/b9f3f290bbd38c3ab'
export const exchange_guide='http://guanwei.zgjy518.com/video/a1e9d77e95b5cf993'
export const special_class='http://guanwei.zgjy518.com/video/b5a2661f6a2b763e'
export const public_resource = 'https://public.jyzqsh.com:447/jywtg'//静态图片资源
export const user_check='/ashx/User_Login.ashx'//用户登录
export const user_record = '/ashx/user_Record.ashx'//用户发送模版消息记录
export const Article_browse_Record= '/ashx/Article_browse_Record.ashx'//文章点击记录
export const Video_browse_Record= '/ashx/Video_browse_Record.ashx'//视频点击观看记录