export const USERCHECK_REQUEST_POST = 'USERCHECK_REQUEST_POST'
export const USERCHECK_RECEIVED='USERCHECK_RECEIVED'
export const USERCHECK_ERROR='USERCHECK_ERROR'
export const USER_LOGOUT='USER_LOGOUT'